spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: huyulong
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
server:
  port: 8081